version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  reviewers:
  - AMS21
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  reviewers:
  - AMS21
